//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Oprum Member</summary>
	[PublishedContentModel("oprumMember")]
	public partial class OprumMember : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "oprumMember";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public OprumMember(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<OprumMember, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Apt. #
		///</summary>
		[ImplementPropertyType("aptNumber")]
		public string AptNumber
		{
			get { return this.GetPropertyValue<string>("aptNumber"); }
		}

		///<summary>
		/// Avatar
		///</summary>
		[ImplementPropertyType("avatar")]
		public IEnumerable<IPublishedContent> Avatar
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("avatar"); }
		}

		///<summary>
		/// Birthday
		///</summary>
		[ImplementPropertyType("birthday")]
		public DateTime Birthday
		{
			get { return this.GetPropertyValue<DateTime>("birthday"); }
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("city")]
		public string City
		{
			get { return this.GetPropertyValue<string>("city"); }
		}

		///<summary>
		/// Department
		///</summary>
		[ImplementPropertyType("department")]
		public string Department
		{
			get { return this.GetPropertyValue<string>("department"); }
		}

		///<summary>
		/// Division
		///</summary>
		[ImplementPropertyType("division")]
		public string Division
		{
			get { return this.GetPropertyValue<string>("division"); }
		}

		///<summary>
		/// Emergency Contact
		///</summary>
		[ImplementPropertyType("emergencyContact")]
		public string EmergencyContact
		{
			get { return this.GetPropertyValue<string>("emergencyContact"); }
		}

		///<summary>
		/// Friendly Name
		///</summary>
		[ImplementPropertyType("friendlyName")]
		public string FriendlyName
		{
			get { return this.GetPropertyValue<string>("friendlyName"); }
		}

		///<summary>
		/// Gender
		///</summary>
		[ImplementPropertyType("gender")]
		public string Gender
		{
			get { return this.GetPropertyValue<string>("gender"); }
		}

		///<summary>
		/// Hire Date
		///</summary>
		[ImplementPropertyType("hireDate")]
		public DateTime HireDate
		{
			get { return this.GetPropertyValue<DateTime>("hireDate"); }
		}

		///<summary>
		/// Last Name
		///</summary>
		[ImplementPropertyType("lastName")]
		public string LastName
		{
			get { return this.GetPropertyValue<string>("lastName"); }
		}

		///<summary>
		/// Legal First Name
		///</summary>
		[ImplementPropertyType("legalFirstName")]
		public string LegalFirstName
		{
			get { return this.GetPropertyValue<string>("legalFirstName"); }
		}

		///<summary>
		/// Middle Initial
		///</summary>
		[ImplementPropertyType("middleInitial")]
		public string MiddleInitial
		{
			get { return this.GetPropertyValue<string>("middleInitial"); }
		}

		///<summary>
		/// Office Extension
		///</summary>
		[ImplementPropertyType("officeExtension")]
		public string OfficeExtension
		{
			get { return this.GetPropertyValue<string>("officeExtension"); }
		}

		///<summary>
		/// PaperWise Password
		///</summary>
		[ImplementPropertyType("paperWisePassword")]
		public object PaperWisePassword
		{
			get { return this.GetPropertyValue("paperWisePassword"); }
		}

		///<summary>
		/// PaperWise Username
		///</summary>
		[ImplementPropertyType("paperWiseUsername")]
		public string PaperWiseUsername
		{
			get { return this.GetPropertyValue<string>("paperWiseUsername"); }
		}

		///<summary>
		/// Personal Phone Number
		///</summary>
		[ImplementPropertyType("personalPhoneNumber")]
		public string PersonalPhoneNumber
		{
			get { return this.GetPropertyValue<string>("personalPhoneNumber"); }
		}

		///<summary>
		/// State
		///</summary>
		[ImplementPropertyType("state")]
		public string State
		{
			get { return this.GetPropertyValue<string>("state"); }
		}

		///<summary>
		/// Street Address
		///</summary>
		[ImplementPropertyType("streetAddress")]
		public string StreetAddress
		{
			get { return this.GetPropertyValue<string>("streetAddress"); }
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}

		///<summary>
		/// Zip Code
		///</summary>
		[ImplementPropertyType("zipCode")]
		public string ZipCode
		{
			get { return this.GetPropertyValue<string>("zipCode"); }
		}
	}
}
